		<ul id="menuSecondary" class="clearfix">
 			<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'gallery','action'=>'index'), 'default', true) ?>"><strong>GALLERY</strong></a></li>
 		  	<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'gallery','action'=>'album'), 'default', true) ?>"><strong>ALBUM</strong></a></li>
 	<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'gallery','action'=>'images'), 'default', true) ?>"><strong>IMAGES</strong></a></li>
 	<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'gallery','action'=>'uploadimages'), 'default', true) ?>"><strong>UPLOAD IMAGES</strong></a></li>
 		  	
 		  	<li class="selected"><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'gallery','action'=>'albumdelete'), 'default', false) ?>"><strong>DELETE: <?= $this->album->album_title ?></strong></a></li>

 		  	
 		  	
  		</ul>




	
			
	<h1>Delete Album</h1>
	
	<p>Vuoi eliminare l' album  <strong><?= $this->album->album_title ?></strong> ? </p>
	<a href="/admin/gallery/albumdelete/id/<?= $this->album->album_id ?>/confirm/yes">YES</a> or <a href="/admin/gallery/album/">NO</a>
	
	
	
        <br />