	<ul id="menuSecondary" class="clearfix">
		<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'posts','action'=>'index'), 'default', true) ?>"><strong>EDIT</strong></a></li>
		<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'posts','action'=>'new'), 'default', true) ?>"><strong>WRITE</strong></a></li>
		<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'posts','action'=>'categories'), 'default', true) ?>"><strong>CATEGORIES</strong></a></li>
 		  	
 		  	<li class="selected"><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'posts','action'=>'delete'), 'default', false) ?>"><strong>DELETE: <?= $this->post['post_title'] ?></strong></a></li>

  		</ul>
	
			
	<h1>Delete Post</h1>
	
	<p>Vuoi eliminare l' articolo  <?= $this->post['post_title'] ?> ? </p>
	<a href="/admin/posts/delete/id/<?= $this->post['post_id'] ?>/confirm/yes">YES</a> or <a href="/admin/posts/">NO</a>
	
	
	
        <br />