		<ul id="menuSecondary" class="clearfix">
 			<li><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'pages','action'=>'index'), 'default', true) ?>"><strong>EDIT</strong></a></li>
 		  	<li class="selected"><a href="<?= $this->url(array('module'=>'admin', 'controller'=>'pages','action'=>'new'), 'default', true) ?>"><strong>NEW</strong></a></li>
  		</ul>

	<h1>Add new page</h1>
<form id="form1" name="form1" method="post" action="">

<div id="sinistra">

	      
    <input type="text" name="page_title" id="page_title" size="50" style="width: 590px" />

<br />
  <br />
  <br />
  <textarea name="page_content" id="page_content" style="width:600px; height: 500px;"></textarea>

<?php echo $this->setupEditor( 'page_content' ); ?>


</div>

<div id="destra">
<?= $this->accordion('.accordionClose', true); ?>
<?= $this->accordion('.accordion'); ?>



  <input type="submit" name="button" id="button" value="Save" />
  
    <?= $this->button('#button'); ?>

  <br />
  
<div class="accordion">
  <h3><a href="#">Meta Tag</a></h3>
  <div>


<h4>Description</h4>
<textarea name="page_description" rows="7" id="page_description" style="width: 200px"></textarea>


<h4>Keywords</h4>
<textarea name="page_keywords" rows="6" id="page_keywords" style="width: 200px"></textarea>


</div></div>


<div class="accordionClose">
  <h3><a href="#">System</a></h3>
  <div>


<h4>Page:</h4>
<input type="text" name="page_controller" id="page_controller" style="width: 200px" />
 
<h4>SubPage:</h4>
<input type="text" name="page_action" id="page_action" style="width: 200px" />

</div></div>

</div>
</form>

<div class="clear"></div>