<?php if ($this->pageCount): ?>
<div class="pagination clearfix">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  &nbsp;<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo;</a> 
<?php else: ?>
 <!--  <span class="disabled">&lt; Previous</span> | -->
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    &nbsp;<a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> 
  <?php else: ?>
  <?php echo '&nbsp;<strong>'.$page.'</strong>'; ?>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  &nbsp;<a href="<?php echo $this->url(array('page' => $this->next)); ?>">&raquo;</a>
<?php else: ?>
  <!-- <span class="disabled">Next &gt;</span> -->
<?php endif; ?>
</div>
<?php endif; ?>

<?php
/*
 * Drop down paginaton example
 */
/*
?>
<?php if ($this->pageCount): ?>
<select id="paginationControl" size="1">
<?php foreach ($this->pagesInRange as $page): ?>
  <?php $selected = ($page == $this->current) ? ' selected="selected"' : ''; ?>
  <option value="<?php
        echo $this->url(array('page' => $page));?>"<?php echo $selected ?>>
    <?php echo $page; ?>
  </option>
<?php endforeach; ?>
</select>
<?php endif; ?>

<script type="text/javascript"
     src="http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.2/prototype.js">
</script>
<script type="text/javascript">
$('paginationControl').observe('change', function() {
    window.location = this.options[this.selectedIndex].value;
})
</script>
*/?>