<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
	<head>  
  		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  		
		<?= $this->headTitle() ?>
		<?= $this->headMeta() ?>

 		<?= $this->headLink()->prependStylesheet('/css/global.css') 
 							 ->prependAlternate('/rss', 'application/rss+xml', 'RSS')
 		?>
		
		<?= $this->jQuery()->setVersion('1.4.4')
							->setUiVersion('1.8.8')
							->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/blitzer/jquery-ui.css'); ?>  		
	
	</head> 

	<body>
		
		<div id="content">
			<div id="header">
				<h3 class="tagline"><?= $this->Meme_Setting_get('tagline') ?></h3>
				<h1><?= $this->Meme_Setting_get('sitetitle') ?></h1>
				
				
				<ul id="menu">
					<li><a href="/">Home</a></li>
					<li><a href="/articles">Articles</a></li>
					<li><a href="/products">Products</a></li>
				</ul>
				
				<div class="clear"></div>

			</div>
			<div id="main">
				<?= $this->layout()->content ?>
			</div>
			
			<div id="footer">Powered by <a href="http://memecms.com" target="_blank">MEME CMS</a>
				<br /><br />
			</div>
		</div>
		
	</body>
</html>